slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping

    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    
    correlation_search_space_dimension: 2.0
    correlation_search_space_resolution: 0.05
    correlation_search_space_smear_deviation: 0.1
    
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    
    link_match_minimum_response_fine: 0.65
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 0.1
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.6
    transform_publish_period: 0.05
    map_update_interval: 2.0
    throttle_scans: 1
    scan_buffer_size: 100
    scan_subscriber_queue_size: 100
    resolution: 0.05
    max_laser_range: 10.0
    use_scan_matching: true
